language: python

python:
  - 3.7

install:
  - pip install importlib-metadata --upgrade
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test polls 

after_script:
  - coveralls
 
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"
  app: "swe1-app-alt"
  env: "django-env-swe-app-alt"
  bucket_name: "elasticbeanstalk-us-west-2-032360129501"
  on:
    branch: main